package com.example.vaadingae;

import org.vaadin.vaadinvisualizations.AnnotatedTimeLine;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class GraphTab extends CustomComponent {

	/**
	 * 
	 */
	private static final long serialVersionUID = 142253757813872614L;
	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private AnnotatedTimeLine annotatedTimeLine_1;
	@AutoGenerated
	private Button button_1;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */


	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public GraphTab() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// button_1
		button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		mainLayout.addComponent(button_1);
		
		// annotatedTimeLine_1
		annotatedTimeLine_1 = new AnnotatedTimeLine();
		annotatedTimeLine_1.setImmediate(false);
		annotatedTimeLine_1.setWidth("100.0%");
		annotatedTimeLine_1.setHeight("100.0%");
		mainLayout.addComponent(annotatedTimeLine_1);
		
		return mainLayout;
	}

}
