package com.example.vaadingae;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class LedgerComposite extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Table table_1;
	@AutoGenerated
	private HorizontalLayout topLayout;
	@AutoGenerated
	private Button btnGo;
	@AutoGenerated
	private PopupDateField endDate;
	@AutoGenerated
	private Label lblEnd;
	@AutoGenerated
	private PopupDateField startDate;
	@AutoGenerated
	private Label lblStart;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public LedgerComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// topLayout
		topLayout = buildTopLayout();
		mainLayout.addComponent(topLayout);
		
		// table_1
		table_1 = new Table();
		table_1.setImmediate(false);
		table_1.setWidth("100.0%");
		table_1.setHeight("-1px");
		mainLayout.addComponent(table_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildTopLayout() {
		// common part: create layout
		topLayout = new HorizontalLayout();
		topLayout.setImmediate(false);
		topLayout.setWidth("100.0%");
		topLayout.setHeight("-1px");
		topLayout.setMargin(false);
		
		// lblStart
		lblStart = new Label();
		lblStart.setImmediate(false);
		lblStart.setWidth("-1px");
		lblStart.setHeight("-1px");
		lblStart.setValue("Start");
		topLayout.addComponent(lblStart);
		
		// startDate
		startDate = new PopupDateField();
		startDate.setImmediate(false);
		startDate.setWidth("-1px");
		startDate.setHeight("-1px");
		startDate.setInvalidAllowed(false);
		startDate.setResolution(4);
		topLayout.addComponent(startDate);
		
		// lblEnd
		lblEnd = new Label();
		lblEnd.setImmediate(false);
		lblEnd.setWidth("-1px");
		lblEnd.setHeight("-1px");
		lblEnd.setValue("End");
		topLayout.addComponent(lblEnd);
		
		// endDate
		endDate = new PopupDateField();
		endDate.setImmediate(false);
		endDate.setWidth("-1px");
		endDate.setHeight("-1px");
		endDate.setInvalidAllowed(false);
		endDate.setResolution(4);
		topLayout.addComponent(endDate);
		
		// btnGo
		btnGo = new Button();
		btnGo.setCaption("Go");
		btnGo.setImmediate(false);
		btnGo.setWidth("-1px");
		btnGo.setHeight("-1px");
		topLayout.addComponent(btnGo);
		
		return topLayout;
	}

}
