package com.example.vaadingae;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class TabPanel extends CustomComponent {

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private TabSheet tabSheet_1;
	@AutoGenerated
	private Panel graphTabPanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_3;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Panel ledgerTabPanel;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private LedgerComposite ledgerComposite;
	@AutoGenerated
	private Panel managerTabPanel;
	@AutoGenerated
	private VerticalLayout managerTabPanelRootLayout;
	@AutoGenerated
	private ManagerComposite managerComposite_1;




	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */




	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TabPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}


	

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// tabSheet_1
		tabSheet_1 = buildTabSheet_1();
		mainLayout.addComponent(tabSheet_1);
		
		return mainLayout;
	}




	@AutoGenerated
	private TabSheet buildTabSheet_1() {
		// common part: create layout
		tabSheet_1 = new TabSheet();
		tabSheet_1.setImmediate(true);
		tabSheet_1.setWidth("100.0%");
		tabSheet_1.setHeight("-1px");
		
		// managerTabPanel
		managerTabPanel = buildManagerTabPanel();
		tabSheet_1.addTab(managerTabPanel, "Manage", null);
		
		// ledgerTabPanel
		ledgerTabPanel = buildLedgerTabPanel();
		tabSheet_1.addTab(ledgerTabPanel, "Ledger", null);
		
		// graphTabPanel
		graphTabPanel = buildGraphTabPanel();
		tabSheet_1.addTab(graphTabPanel, "Graph", null);
		
		return tabSheet_1;
	}




	@AutoGenerated
	private Panel buildManagerTabPanel() {
		// common part: create layout
		managerTabPanel = new Panel();
		managerTabPanel.setImmediate(false);
		managerTabPanel.setWidth("100.0%");
		managerTabPanel.setHeight("-1px");
		
		// managerTabPanelRootLayout
		managerTabPanelRootLayout = buildManagerTabPanelRootLayout();
		managerTabPanel.setContent(managerTabPanelRootLayout);
		
		return managerTabPanel;
	}




	@AutoGenerated
	private VerticalLayout buildManagerTabPanelRootLayout() {
		// common part: create layout
		managerTabPanelRootLayout = new VerticalLayout();
		managerTabPanelRootLayout.setImmediate(false);
		managerTabPanelRootLayout.setWidth("100.0%");
		managerTabPanelRootLayout.setHeight("-1px");
		managerTabPanelRootLayout.setMargin(true);
		managerTabPanelRootLayout.setSpacing(true);
		
		// managerComposite_1
		managerComposite_1 = new ManagerComposite();
		managerComposite_1.setImmediate(false);
		managerComposite_1.setWidth("100.0%");
		managerComposite_1.setHeight("-1px");
		managerTabPanelRootLayout.addComponent(managerComposite_1);
		
		return managerTabPanelRootLayout;
	}




	@AutoGenerated
	private Panel buildLedgerTabPanel() {
		// common part: create layout
		ledgerTabPanel = new Panel();
		ledgerTabPanel.setImmediate(false);
		ledgerTabPanel.setWidth("100.0%");
		ledgerTabPanel.setHeight("-1px");
		
		// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
		ledgerTabPanel.setContent(verticalLayout_2);
		
		return ledgerTabPanel;
	}




	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("-1px");
		verticalLayout_2.setMargin(true);
		verticalLayout_2.setSpacing(true);
		
		// ledgerComposite
		ledgerComposite = new LedgerComposite();
		ledgerComposite.setImmediate(false);
		ledgerComposite.setWidth("100.0%");
		ledgerComposite.setHeight("-1px");
		verticalLayout_2.addComponent(ledgerComposite);
		
		return verticalLayout_2;
	}




	@AutoGenerated
	private Panel buildGraphTabPanel() {
		// common part: create layout
		graphTabPanel = new Panel();
		graphTabPanel.setImmediate(false);
		graphTabPanel.setWidth("100.0%");
		graphTabPanel.setHeight("-1px");
		
		// verticalLayout_3
		verticalLayout_3 = buildVerticalLayout_3();
		graphTabPanel.setContent(verticalLayout_3);
		
		return graphTabPanel;
	}




	@AutoGenerated
	private VerticalLayout buildVerticalLayout_3() {
		// common part: create layout
		verticalLayout_3 = new VerticalLayout();
		verticalLayout_3.setImmediate(false);
		verticalLayout_3.setWidth("100.0%");
		verticalLayout_3.setHeight("-1px");
		verticalLayout_3.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("TBD");
		verticalLayout_3.addComponent(label_1);
		
		return verticalLayout_3;
	}

}
